apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: simple-daily-games
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
        - name: postgres-secret-volume
          secret:
            secretName: postgres-secret
      containers:
        - name: api
          image: kingbrady/simple-daily-games-api:1.1.1
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOSTNAME
              value: postgres.postgres.svc.cluster.local

