apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-daily-games-pipeline-sa
  namespace: simple-daily-games
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-daily-games-pipeline-sa-token
  namespace: simple-daily-games
  annotations:
    kubernetes.io/service-account.name: simple-daily-games-pipeline-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: simple-daily-games-pipeline-sa-admin
  namespace: simple-daily-games
subjects:
  - kind: ServiceAccount
    name: simple-daily-games-pipeline-sa
    namespace: simple-daily-games
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
